#ifndef LAYOUT_H
#define LAYOUT_H
/* Wakizashi Default Latin+Cyrillic
 * generated by Timur Ismagilov's waki_gen.rb
 * on 2019-05-06 23:09:10 +0500
 *
 * https://github.com/bouncepaw/wakizashi
 */
void exec_chord(chord currc) {
  currc = ~currc % (1 << 11);
  Serial.print("Execute chord ");
  debug_print(currc);

  switch (Layer::curr) {
    case Layer::modificator: {
      switch (currc) {
        case 0b10000000000: {
            Keyboard.print('o');
            break;
        }
        case 0b01000000000: {
            Keyboard.print('a');
            break;
        }
        case 0b00100000000: {
            Keyboard.print('p');
            break;
        }
        case 0b00010000000: {
            Keyboard.print('e');
            break;
        }
        case 0b00001000000: {
            Keyboard.print('h');
            break;
        }
        case 0b00000100000: {
            Keyboard.print('s');
            break;
        }
        case 0b00000010000: {
            Keyboard.print('n');
            break;
        }
        case 0b00000001000: {
            Keyboard.print('i');
            break;
        }
        case 0b00000000100: {
            Keyboard.print(' ');
            break;
        }
        case 0b00000000010: {
            Keyboard.print(',');
            break;
        }
        case 0b00000000001: {
            Keyboard.print('.');
            break;
        }
        case 0b10000000100: {
            Keyboard.print('O');
            break;
        }
        case 0b01000000100: {
            Keyboard.print('A');
            break;
        }
        case 0b00100000100: {
            Keyboard.print('P');
            break;
        }
        case 0b00010000100: {
            Keyboard.print('E');
            break;
        }
        case 0b00001000100: {
            Keyboard.print('H');
            break;
        }
        case 0b00000100100: {
            Keyboard.print('S');
            break;
        }
        case 0b00000010100: {
            Keyboard.print('N');
            break;
        }
        case 0b00000001100: {
            Keyboard.print('I');
            break;
        }
        case 0b10000000010: {
            Keyboard.print('8');
            break;
        }
        case 0b01000000010: {
            Keyboard.print('4');
            break;
        }
        case 0b00100000010: {
            Keyboard.print('2');
            break;
        }
        case 0b00010000010: {
            Keyboard.print('1');
            break;
        }
        case 0b00001000010: {
            Keyboard.print(':');
            break;
        }
        case 0b00000100010: {
            Keyboard.print('"');
            break;
        }
        case 0b00000010010: {
            Keyboard.print('\'');
            break;
        }
        case 0b00000001010: {
            Keyboard.print(';');
            break;
        }
        case 0b10000000001: {
            Keyboard.print('o');
            break;
        }
        case 0b01000000001: {
            Keyboard.print('a');
            break;
        }
        case 0b00100000001: {
            Keyboard.print('p');
            break;
        }
        case 0b00010000001: {
            Keyboard.print('e');
            break;
        }
        case 0b00001000001: {
            Keyboard.print('h');
            break;
        }
        case 0b00000100001: {
            Keyboard.print('s');
            break;
        }
        case 0b00000010001: {
            Keyboard.print('n');
            break;
        }
        case 0b00000001001: {
            Keyboard.print('i');
            break;
        }
      }
      if (!(currc & 1)) { Layer::back(); }
      break;
    }
    case Layer::latin: {
      switch (currc) {
        case 0b10000000000: {
            Keyboard.print('o');
            break;
        }
        case 0b01000000000: {
            Keyboard.print('a');
            break;
        }
        case 0b00100000000: {
            Keyboard.print('p');
            break;
        }
        case 0b00010000000: {
            Keyboard.print('e');
            break;
        }
        case 0b00001000000: {
            Keyboard.print('h');
            break;
        }
        case 0b00000100000: {
            Keyboard.print('s');
            break;
        }
        case 0b00000010000: {
            Keyboard.print('n');
            break;
        }
        case 0b00000001000: {
            Keyboard.print('i');
            break;
        }
        case 0b00000000100: {
            Keyboard.print(' ');
            break;
        }
        case 0b00000000010: {
            Keyboard.print(',');
            break;
        }
        case 0b00000000001: {
            Keyboard.print('.');
            break;
        }
        case 0b10000000100: {
            Keyboard.print('O');
            break;
        }
        case 0b01000000100: {
            Keyboard.print('A');
            break;
        }
        case 0b00100000100: {
            Keyboard.print('P');
            break;
        }
        case 0b00010000100: {
            Keyboard.print('E');
            break;
        }
        case 0b00001000100: {
            Keyboard.print('H');
            break;
        }
        case 0b00000100100: {
            Keyboard.print('S');
            break;
        }
        case 0b00000010100: {
            Keyboard.print('N');
            break;
        }
        case 0b00000001100: {
            Keyboard.print('I');
            break;
        }
        case 0b10000000010: {
            Keyboard.print('8');
            break;
        }
        case 0b01000000010: {
            Keyboard.print('4');
            break;
        }
        case 0b00100000010: {
            Keyboard.print('2');
            break;
        }
        case 0b00010000010: {
            Keyboard.print('1');
            break;
        }
        case 0b00001000010: {
            Keyboard.print(':');
            break;
        }
        case 0b00000100010: {
            Keyboard.print('"');
            break;
        }
        case 0b00000010010: {
            Keyboard.print('\'');
            break;
        }
        case 0b00000001010: {
            Keyboard.print(';');
            break;
        }
        case 0b10000000001: {
            Layer::enter_mod(Mod::ctrl);
            break;
        }
        case 0b01000000001: {
            Layer::enter_mod(Mod::altl);
            break;
        }
        case 0b00100000001: {
            Keyboard.press(KEY_UP_ARROW);
            Keyboard.release(KEY_UP_ARROW);
            break;
        }
        case 0b00010000001: {
            Layer::enter_mod(Mod::super);
            break;
        }
        case 0b00001000001: {
            Layer::enter_mod(Mod::shift);
            break;
        }
        case 0b00000100001: {
            Keyboard.press(KEY_LEFT_ARROW);
            Keyboard.release(KEY_LEFT_ARROW);
            break;
        }
        case 0b00000010001: {
            Keyboard.press(KEY_DOWN_ARROW);
            Keyboard.release(KEY_DOWN_ARROW);
            break;
        }
        case 0b00000001001: {
            Keyboard.press(KEY_RIGHT_ARROW);
            Keyboard.release(KEY_RIGHT_ARROW);
            break;
        }
        case 0b10000000011: {
            Keyboard.print("to ");
            break;
        }
        case 0b01000000011: {
            Keyboard.print("and ");
            break;
        }
        case 0b00100000011: {
            Keyboard.print("of ");
            break;
        }
        case 0b00010000011: {
            Keyboard.print("the ");
            break;
        }
        case 0b00001000011: {
            Keyboard.print("a ");
            break;
        }
        case 0b00000100011: {
            Keyboard.print("in ");
            break;
        }
        case 0b00000010011: {
            Keyboard.print("that ");
            break;
        }
        case 0b00000001011: {
            Keyboard.print("be ");
            break;
        }
        case 0b10001000000: {
            Keyboard.print('r');
            break;
        }
        case 0b01000100000: {
            Keyboard.print('l');
            break;
        }
        case 0b00100010000: {
            Keyboard.print('d');
            break;
        }
        case 0b00010001000: {
            Keyboard.print('u');
            break;
        }
        case 0b10001000100: {
            Keyboard.print('R');
            break;
        }
        case 0b01000100100: {
            Keyboard.print('L');
            break;
        }
        case 0b00100010100: {
            Keyboard.print('D');
            break;
        }
        case 0b00010001100: {
            Keyboard.print('U');
            break;
        }
        case 0b00100010010: {
            Keyboard.print('(');
            break;
        }
        case 0b00010001010: {
            Keyboard.print(')');
            break;
        }
        case 0b10001000001: {
            Keyboard.press(KEY_PAGE_DOWN);
            Keyboard.release(KEY_PAGE_DOWN);
            break;
        }
        case 0b01000100001: {
            Keyboard.press(KEY_PAGE_UP);
            Keyboard.release(KEY_PAGE_UP);
            break;
        }
        case 0b00100010001: {
            Keyboard.press(KEY_TAB);
            Keyboard.release(KEY_TAB);
            break;
        }
        case 0b00010001001: {
            Keyboard.press(KEY_ESC);
            Keyboard.release(KEY_ESC);
            break;
        }


        case 0b11000000000: {
            Keyboard.print("th");
            break;
        }
        case 0b01100000000: {
            Keyboard.print('c');
            break;
        }
        case 0b00110000000: {
            Keyboard.print('m');
            break;
        }
        case 0b10010000000: {
            Keyboard.print('w');
            break;
        }
        case 0b10100000000: {
            Keyboard.print('[');
            break;
        }
        case 0b01010000000: {
            Keyboard.print(']');
            break;
        }
        case 0b00001100000: {
            Keyboard.print('y');
            break;
        }
        case 0b00000110000: {
            Keyboard.print('f');
            break;
        }
        case 0b00000011000: {
            Keyboard.print('g');
            break;
        }
        case 0b00001001000: {
            Keyboard.print('t');
            break;
        }
        case 0b00001010000: {
            Keyboard.print('{');
            break;
        }
        case 0b00000101000: {
            Keyboard.print('}');
            break;
        }
        case 0b11000000100: {
            Keyboard.print("Th");
            break;
        }
        case 0b01100000100: {
            Keyboard.print('C');
            break;
        }
        case 0b00110000100: {
            Keyboard.print('M');
            break;
        }
        case 0b10010000100: {
            Keyboard.print('W');
            break;
        }
        case 0b10100000100: {
            Keyboard.print('<');
            break;
        }
        case 0b01010000100: {
            Keyboard.print('>');
            break;
        }
        case 0b00001100100: {
            Keyboard.print('Y');
            break;
        }
        case 0b00000110100: {
            Keyboard.print('F');
            break;
        }
        case 0b00000011100: {
            Keyboard.print('G');
            break;
        }
        case 0b00001001100: {
            Keyboard.print('T');
            break;
        }
        case 0b00001010100: {
            Keyboard.print('~');
            break;
        }
        case 0b00000101100: {
            Keyboard.print('`');
            break;
        }
        case 0b11000000010: {
            Keyboard.print('!');
            break;
        }
        case 0b01100000010: {
            Keyboard.print('6');
            break;
        }
        case 0b00110000010: {
            Keyboard.print('3');
            break;
        }
        case 0b10010000010: {
            Keyboard.print('9');
            break;
        }
        case 0b10100000010: {
            Keyboard.print('+');
            break;
        }
        case 0b01010000010: {
            Keyboard.print('0');
            break;
        }
        case 0b00001100010: {
            Keyboard.print('{');
            break;
        }
        case 0b00000110010: {
            Keyboard.print('}');
            break;
        }
        case 0b00000011010: {
            Keyboard.print('/');
            break;
        }
        case 0b00001001010: {
            Keyboard.print('\\');
            break;
        }
        case 0b00001010010: {
            Keyboard.print('*');
            break;
        }
        case 0b11000000011: {
            Keyboard.print("the ");
            break;
        }
        case 0b01100000011: {
            Keyboard.print("you ");
            break;
        }
        case 0b00110000011: {
            Keyboard.print("we ");
            break;
        }
        case 0b10010000011: {
            Keyboard.print("they ");
            break;
        }
        case 0b10100000011: {
            Keyboard.print("he");
            break;
        }
        case 0b01010000011: {
            Keyboard.print("she");
            break;
        }
        case 0b00001100011: {
            Keyboard.print("I ");
            break;
        }
        case 0b00000110011: {
            Keyboard.print("are ");
            break;
        }
        case 0b00000011011: {
            Keyboard.print("is ");
            break;
        }
        case 0b00001001011: {
            Keyboard.print("it ");
            break;
        }
        case 0b00001010011: {
            Keyboard.print("an ");
            break;
        }
        case 0b00000101011: {
            Keyboard.print("a ");
            break;
        }
        case 0b11100000000: {
            Keyboard.print('b');
            break;
        }
        case 0b11010000000: {
            Keyboard.print('v');
            break;
        }
        case 0b01110000000: {
            Keyboard.print('k');
            break;
        }
        case 0b10110000000: {
            Keyboard.print('j');
            break;
        }
        case 0b00001110000: {
            Keyboard.print('x');
            break;
        }
        case 0b00001101000: {
            Keyboard.print('q');
            break;
        }
        case 0b00000111000: {
            Keyboard.print('z');
            break;
        }
        case 0b11100000100: {
            Keyboard.print('B');
            break;
        }
        case 0b11010000100: {
            Keyboard.print('V');
            break;
        }
        case 0b01110000100: {
            Keyboard.print('K');
            break;
        }
        case 0b10110000100: {
            Keyboard.print('J');
            break;
        }
        case 0b00001110100: {
            Keyboard.print('X');
            break;
        }
        case 0b00001101100: {
            Keyboard.print('Q');
            break;
        }
        case 0b00000111100: {
            Keyboard.print('Z');
            break;
        }
        case 0b11100000010: {
            Keyboard.print('#');
            break;
        }
        case 0b11010000010: {
            Keyboard.print('|');
            break;
        }
        case 0b01110000010: {
            Keyboard.print('?');
            break;
        }
        case 0b10110000010: {
            Keyboard.print('=');
            break;
        }
        case 0b11110000000: {
            Keyboard.print('-');
            break;
        }
        case 0b11001100000: {
            Keyboard.print('^');
            break;
        }
        case 0b01100110000: {
            Keyboard.print('%');
            break;
        }
        case 0b00110011000: {
            Keyboard.print('&');
            break;
        }
        case 0b10011001000: {
            Keyboard.print('@');
            break;
        }
      }

      break;
    }
  }
}
#endif
